package Casino;

import Players.Player;
import java.util.ArrayList;

public class BlackJack extends javax.swing.JFrame {

    Player player;
    ArrayList<Integer> deck = new ArrayList<>();
    int sum;
    
    public BlackJack() {
        initComponents();
    }
    
    public BlackJack(Player p) {
        initComponents();
        player = p; 
        hitButton.setEnabled(false); 
        standButton.setEnabled(false);
        for (int num=1; num<=13; num++)
            for (int k=0; k<4; k++)
                deck.add(num); 
    }
    
    public void reinstateDeck(){
        ArrayList<Integer> temp = new ArrayList<>();
        for (int num=1; num<=13; num++)
            for (int k=0; k<4; k++)
                temp.add(num);
        deck = temp; 
    }
    
    public void win(){
        ResultBox.setText("Congratulations! You won $60!");
        player.addMoney(60);
    }
    
    public void loss(){
        ResultBox.setText("Sorry! Try again");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        BoxOne = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BoxTwo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BoxThree = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hitButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        standButton = new javax.swing.JButton();
        ResultBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("BLACKJACK");

        ExitButton.setText("Exit Game");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        BoxOne.setEditable(false);
        BoxOne.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        BoxOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxOneActionPerformed(evt);
            }
        });

        jLabel2.setText("Current Card");

        jLabel3.setText("Current Sum");

        BoxTwo.setEditable(false);
        BoxTwo.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        BoxTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxTwoActionPerformed(evt);
            }
        });

        jLabel4.setText("Computer Sum:");

        BoxThree.setEditable(false);
        BoxThree.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        BoxThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxThreeActionPerformed(evt);
            }
        });

        jLabel5.setText("Get closer to 21 than the computer, but don't go over! Win = $60");

        hitButton.setText("Hit");
        hitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitButtonActionPerformed(evt);
            }
        });

        PlayButton.setText("Play ($40)");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        standButton.setText("Stand");
        standButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(ExitButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BoxOne, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(BoxTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(BoxThree, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(standButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(ResultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxThree, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxOne, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ResultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void BoxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxOneActionPerformed

    private void BoxTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxTwoActionPerformed

    private void BoxThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxThreeActionPerformed

    private void hitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitButtonActionPerformed
        int num3 = deck.remove((int)(Math.random()*deck.size())); 
        BoxOne.setText(Integer.toString(num3)); 
        if (num3>10)
            num3=10;
        if (num3==1 && sum>21){
            if ((sum+10)>21)
                num3=1; 
            else
                num3=10; 
        }
        sum+=num3; 
        BoxTwo.setText(Integer.toString(sum));
        if (sum>21){
            hitButton.setEnabled(false); 
            standButton.setEnabled(false);
            PlayButton.setEnabled(true);
            ResultBox.setText("Game Over!"); 
            loss();
        }
    }//GEN-LAST:event_hitButtonActionPerformed

    private void standButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standButtonActionPerformed
        int computerSum = (int)(Math.random()*9) + 16;
        BoxThree.setText(Integer.toString(computerSum));
        if (computerSum==sum)
            computerSum++;
        if (computerSum > 21)
            win(); 
        else if (computerSum <= 21){
            if (computerSum>sum)
                loss();
            else
                win();
        }
        hitButton.setEnabled(false); 
        standButton.setEnabled(false);
        PlayButton.setEnabled(true);
        
    }//GEN-LAST:event_standButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        if (player.getMoney()-40 < 0){
            ResultBox.setText("Sorry! You don't have enough money to play.");
        }
        else{
            ResultBox.setText("");
            BoxThree.setText("");
            player.addMoney(-40);
            reinstateDeck(); 
            hitButton.setEnabled(true); 
            standButton.setEnabled(true);
            PlayButton.setEnabled(false);
            int num1 = deck.remove((int)(Math.random()*deck.size())); 
            int num2 = deck.remove((int)(Math.random()*deck.size())); 
            BoxOne.setText(Integer.toString(num2)); 
            if (num1>10)
                num1=10; 
            if (num2>10)
                num2=10;
            sum = num1+num2;
            BoxTwo.setText(Integer.toString(sum));
        }
    }//GEN-LAST:event_PlayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxOne;
    private javax.swing.JTextField BoxThree;
    private javax.swing.JTextField BoxTwo;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JTextField ResultBox;
    private javax.swing.JButton hitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton standButton;
    // End of variables declaration//GEN-END:variables
}
