package Casino;

import Players.Player;
import Players.PlayerList;
import RFID.SimulateCardReadFrame;

public class CasinoFrame extends javax.swing.JFrame {

    public Player player;
    
    public CasinoFrame(){
        initComponents(); 
    }
    
    public CasinoFrame(String id) {
        initComponents();
        PlayerList.playerList.stream().filter((playerTemp) -> (playerTemp.getId().equals(id))).forEach((playerTemp) -> {
            player = playerTemp;
        });
        WelcomeMessage.setText("Welcome to the Casino, " + player.getName() + "!");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        WelcomeMessage = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        SlotMachine = new javax.swing.JButton();
        Money = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        SlotMachine1 = new javax.swing.JButton();
        SlotMachine2 = new javax.swing.JButton();
        SlotMachine3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pick a Game!");

        WelcomeMessage.setEditable(false);
        WelcomeMessage.setBackground(new java.awt.Color(204, 204, 204));
        WelcomeMessage.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        WelcomeMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jToggleButton1.setText("Exit Casino");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        SlotMachine.setBackground(new java.awt.Color(255, 255, 255));
        SlotMachine.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SlotMachine.setText("SLOT MACHINES");
        SlotMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotMachineActionPerformed(evt);
            }
        });

        Money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyActionPerformed(evt);
            }
        });

        jButton2.setText("See Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SlotMachine1.setBackground(new java.awt.Color(255, 255, 255));
        SlotMachine1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SlotMachine1.setText("ROULETTE");
        SlotMachine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotMachine1ActionPerformed(evt);
            }
        });

        SlotMachine2.setBackground(new java.awt.Color(255, 255, 255));
        SlotMachine2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SlotMachine2.setText("BLACKJACK");
        SlotMachine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotMachine2ActionPerformed(evt);
            }
        });

        SlotMachine3.setBackground(new java.awt.Color(255, 255, 255));
        SlotMachine3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SlotMachine3.setText("HIGHER/LOWER");
        SlotMachine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotMachine3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomeMessage, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SlotMachine1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SlotMachine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SlotMachine3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(SlotMachine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1)
                    .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SlotMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlotMachine3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SlotMachine1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlotMachine2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void SlotMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotMachineActionPerformed
        SlotsMachine s = new SlotsMachine(player); 
        s.setVisible(true);
    }//GEN-LAST:event_SlotMachineActionPerformed

    private void MoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Money.setText("$" + player.getMoney());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SlotMachine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotMachine1ActionPerformed
        Roulette r = new Roulette(player); 
        r.setVisible(true); 
    }//GEN-LAST:event_SlotMachine1ActionPerformed

    private void SlotMachine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotMachine2ActionPerformed
        BlackJack b = new BlackJack(player); 
        b.setVisible(true);
    }//GEN-LAST:event_SlotMachine2ActionPerformed

    private void SlotMachine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotMachine3ActionPerformed
        HigherLower h = new HigherLower(player); 
        h.setVisible(true);
    }//GEN-LAST:event_SlotMachine3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasinoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasinoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasinoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasinoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasinoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Money;
    private javax.swing.JButton SlotMachine;
    private javax.swing.JButton SlotMachine1;
    private javax.swing.JButton SlotMachine2;
    private javax.swing.JButton SlotMachine3;
    private javax.swing.JTextField WelcomeMessage;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
