package Casino;

import Players.Player;

public class SlotsMachine extends javax.swing.JFrame {

    int firstNum; 
    int secondNum; 
    int thirdNum; 
    Player player; 
    
    public SlotsMachine(){
        initComponents();
    }
    
    public SlotsMachine(Player p) {
        initComponents();
        player = p; 
    }

    public void updateMoney(){
        if (firstNum!= secondNum && secondNum != thirdNum && thirdNum != firstNum)
            ResultBox.setText("Try Again!");
        else if (firstNum == secondNum && secondNum == thirdNum){
            player.addMoney(550);
            ResultBox.setText("You won $500!");
        }
        else{
            player.addMoney(125);
            ResultBox.setText("You won $75!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BoxOne = new javax.swing.JTextField();
        SpinButton = new javax.swing.JButton();
        BoxTwo = new javax.swing.JTextField();
        BoxThree = new javax.swing.JTextField();
        ResultBox = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("SLOT MACHINE");

        BoxOne.setEditable(false);
        BoxOne.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        BoxOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxOneActionPerformed(evt);
            }
        });

        SpinButton.setBackground(new java.awt.Color(255, 255, 153));
        SpinButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SpinButton.setText("SPIN! ($50)");
        SpinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpinButtonActionPerformed(evt);
            }
        });

        BoxTwo.setEditable(false);
        BoxTwo.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        BoxTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxTwoActionPerformed(evt);
            }
        });

        BoxThree.setEditable(false);
        BoxThree.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        BoxThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxThreeActionPerformed(evt);
            }
        });

        ResultBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ResultBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ExitButton.setText("Exit Game");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ResultBox)
                            .addComponent(SpinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ExitButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxOne, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BoxTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(BoxThree, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(ExitButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxOne, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxThree, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SpinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxOneActionPerformed

    private void SpinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpinButtonActionPerformed
        player.addMoney(-50);
        if (player.getMoney()<0){
            SpinButton.setEnabled(false); 
            ResultBox.setText("You're Bankrupt!");
            player.setMoney(0);
        }
        else{
            firstNum = (int)(Math.random()*9)+1;
            secondNum = (int)(Math.random()*9)+1; 
            thirdNum = (int)(Math.random()*9)+1; 
            BoxOne.setText(Integer.toString(firstNum)); 
            BoxTwo.setText(Integer.toString(secondNum)); 
            BoxThree.setText(Integer.toString(thirdNum)); 
            updateMoney();
        }
    }//GEN-LAST:event_SpinButtonActionPerformed

    private void BoxTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxTwoActionPerformed

    private void BoxThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxThreeActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotsMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxOne;
    private javax.swing.JTextField BoxThree;
    private javax.swing.JTextField BoxTwo;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField ResultBox;
    private javax.swing.JButton SpinButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
